---
profile::unix::groups:
  'filebeat':
    ensure: 'present'
    gid:    '4000'

profile::unix::groups::realize:
  - 'filebeat'

profile::unix::users:
  'filebeat':
    ensure:           'present'
    uid:              '4000'
    gid:              '4000'
    groups:           ['filebeat']
    shell:            '/sbin/nologin'
    home:             '/app/filebeat'
    managehome:       true
    password_max_age: '12'
    password_min_age: '0'
    password:         '!'

profile::unix::users::realize:
  - 'filebeat'

profile::unix::files:
  /app:
    ensure: 'directory'
    owner:  '0'
    group:  '0'
    mode:   '0755'
  /app/filebeat:
    ensure: 'directory'
    owner:  'filebeat'
    group:  'filebeat'
    mode:   '2755'
    require: File[/app]
  /download:
    ensure: 'directory'
    owner:  '0'
    group:  '0'
    mode:   '0755'
  /download/.puppet:
    ensure: 'directory'
    owner:  '0'
    group:  '0'
    mode:   '0755'
  /etc:
    ensure: 'directory'
    owner: '0'
    group: '0'
    mode:  '0755'
  /etc/filebeat:
    ensure: 'directory'
    owner: 'filebeat'
    group: 'filebeat'
    mode:  '0755'
    require: File[/etc]
  /usr/share:
    ensure: 'directory'
    owner:  '0'
    group:  '0'
    mode:   '0755'
  /app/lib:
    ensure: 'directory'
    owner:  '0'
    group:  '0'
    mode:   '0755'
  /app/lib/filebeat:
    ensure: 'directory'
    owner:  'filebeat'
    group:  'filebeat'
    mode:   '2755'
  /app/log:
    ensure: 'directory'
    owner:  '0'
    group:  '0'
    mode:   '0755'
  /app/log/filebeat:
    ensure: 'directory'
    owner:  'filebeat'
    group:  'filebeat'
    mode:   '2775'
    require: File[/app/log]


profile::unix::os::redhat::packages:
  'java-1.8.0-openjdk':
    ensure: latest
  'java-1.8.0-openjdk-devel':
    ensure: latest
  'java-1.8.0-openjdk-headless':
    ensure: latest
  'sudo':
    ensure: latest

profile::devops::secure::filebeat::install::package: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-6.6.0-x86_64.rpm
profile::devops::secure::filebeat::install::download_dir: /download
profile::devops::secure::filebeat::install::filebeat_dir: /app/filebeat

######filebeat Server Settings ##############################

profile::devops::secure::filebeat::config::filebeat_config_file: /etc/filebeat/filebeat.yml
profile::devops::secure::filebeat::config::filebeat_owner: filebeat
profile::devops::secure::filebeat::config::filebeat_group: filebeat

profile::devops::secure::filebeat::config::log_dir:  /app/log/filebeat
profile::devops::secure::filebeat::config::data_dir: /app/lib/filebeat

profile::devops::secure::filebeat::config::init_service_template: profile/devops/secure/filebeat.service.erb
